apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-env
  namespace: stremio
data:
  HTTPPROXY: "on"
  HTTPPROXY_LISTENING_ADDRESS: ":7777"
  FIREWALL_INPUT_PORTS: "7777"
  VPN_SERVICE_PROVIDER: "protonvpn"
  SERVER_COUNTRIES: "Netherlands"
  FREE_ONLY: "on"
  VPN_TYPE: "wireguard"
  WIREGUARD_PRIVATE_KEY: ""
  # OPENVPN_USER: "pvstbpqv592410"
  # OPENVPN_PASSWORD: ""
---
# ---------------------------
# Gluetun Deployment
# ---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: stremio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      containers:
        - name: gluetun
          image: qmcgaw/gluetun
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: gluetun-env
          ports:
            - containerPort: 7777
          livenessProbe:
            exec:
              command: ["/gluetun-entrypoint", "healthcheck"]
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: gluetun
  namespace: stremio
spec:
  selector:
    app: gluetun
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP

