apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  creationTimestamp: "2023-10-11T21:20:28Z"
  generation: 1
  labels:
    name: observability
  name: grafana-tls
  namespace: observability
  ownerReferences:
  - apiVersion: networking.k8s.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Ingress
    name: grafana-ingress
    uid: 39aec9fa-f12c-438d-b1c6-ab5ad4e1bfb0
  resourceVersion: "1054440"
  uid: b0efbe5b-c2a9-4fbc-b0fa-727d679fe048
spec:
  dnsNames:
  - grafana.inner-circle.ovh
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: grafana-tls
  usages:
  - digital signature
  - key encipherment
